spring:
  application:
    name: beyond-medicine-test

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: oldaim
    password: oldaim
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

verification:
  hash:
    secret: b3y0ndM3d1c1n3_S3cur3_K3y_2025