spring:
  application:
    name: beyond-medicine-test

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: oldaim
    password: oldaim
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true

verification:
  hash:
    secret: b3y0ndM3d1c1n3_S3cur3_K3y_2025